Kostya exercises list
Vladnova/sportIsLife pull request #15
Opened 2023-12-13 14:46 UTC by Baltakov

upd stars

2023-12-13 15:10 UTC, Vladnova requested changes
Переглянь стилі, і зміни на var де використовуються найпоширеніші кольори та шрифт

2023-12-13 15:10 UTC, Vladnova commented on src/css/layout/exercises-right-part-filter.css
> +  color: #242424;
Чому не використовуєш var для кольорів і шрифта?
Вони прописані у файлі comman.css

2023-12-13 15:10 UTC, Vladnova commented on src/css/layout/exercises-right-part-filter.css
> +  font-family: DM Sans;
Тут також було написано правильно, але чомусь змінив

2023-12-13 15:26 UTC, Baltakov commented
Та щось не підтягувались. Щас виправлю

2023-12-13 15:28 UTC, Baltakov commented on src/css/layout/exercises-right-part-filter.css
> +  color: #242424;
Щось не підтягувались с коммона. Щас виправлю.

2023-12-14 11:08 UTC, Vladnova submitted a review, later dismissed

2023-12-14 11:10 UTC, merged